workflows:
  ios-dev:
    name: iOS Development Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
      - app_store_credentials
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Build iOS (no codesign)
        script: flutter build ios --no-codesign

      - name: Archive app
        script: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/Runner.xcarchive \
            DEVELOPMENT_TEAM=$CM_APPLE_TEAM_ID \
            CODE_SIGN_STYLE=Automatic \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -allowProvisioningUpdates \
            archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ipa
    artifacts:
      - build/ipa/*.ipa
